apiVersion: v1
kind: Service
metadata:
  name: result
  namespace: global-vote-app
spec:
  type: NodePort
  selector:
    app: result-app
  ports:
  - port: 4000
    targetPort: 4000
    nodePort: 30006
